### ISSUE TITLE
Packages  404  Not Found 

### ISSUE THREAD

**Issue by donfirst** [ArjenSchwarz/fog-report-action#1]
Ign:10 http://deb.debian.org/debian stretch/main all Packages
  Ign:11 http://deb.debian.org/debian stretch-updates/main all Packages
  Err:12 http://deb.debian.org/debian stretch-updates/main amd64 Packages
    404  Not Found
  Reading package lists...
  W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
  W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
  W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
  E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd[64](https://github.com/myorb-ltd/infra-ecr/actions/runs/4936098034/jobs/8823277874#step:2:64)/Packages  404  Not Found [IP: 151.101.130.132 80]
  E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
  E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
  E: Some index files failed to download. They have been ignored, or old ones used instead.
  The command '/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y     wget     ca-certificates     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by donfirst** [comment]
Can't run that github action  - seems that   something need to be updated

**Comment by ArjenSchwarz** [comment]
Thanks @donfirst, I'll have a look if I can see what's going on here.

**Comment by donfirst** [comment]
Finger crossed

**Comment by donfirst** [comment]
Not sure if you  will have time to fix that so for time being  will  comment out that action from my repositories

**Comment by ArjenSchwarz** [comment]
Thank you for your patience. I've fixed the issue (see https://github.com/ArjenSchwarz/fog-report-action/actions/runs/5111611858) and released a new version v1.1.0 that contains this fix.

**Comment by donfirst** [comment]
Will have a look thank you :-)
